### ISSUE TITLE
error in raspbian

### ISSUE THREAD

**Issue by manuhank** [aranajhonny/ig-upload#6]
currently not working on raspbian

im getign this errors at installing:
```
pi@raspberrypi:~ $ sudo npm install -g ig-upload
npm WARN deprecated fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Support
npm WARN deprecated tough-cookie@0.12.1: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
```
and this when uploading (login seems to work fine):

```
pi@raspberrypi:~ $ ig-upload /home/pi/share/Instagramon/fotos/10.jpg 
⠧ Uploading...Unhandled rejection Error: xsel: Can't open display: (null)
: Inappropriate ioctl for device

    at Function.module.exports.sync (/usr/local/lib/node_modules/ig-upload/node_modules/clipboardy/node_modules/execa/index.js:277:26)
    at Object.copySync (/usr/local/lib/node_modules/ig-upload/node_modules/clipboardy/lib/linux.js:31:18)
    at Object.exports.writeSync.input [as writeSync] (/usr/local/lib/node_modules/ig-upload/node_modules/clipboardy/index.js:38:13)
    at /usr/local/lib/node_modules/ig-upload/dist/upload.js:51:24
    at tryCatcher (/usr/local/lib/node_modules/ig-upload/node_modules/instagram-private-api/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/ig-upload/node_modules/instagram-private-api/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/ig-upload/node_modules/instagram-private-api/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/ig-upload/node_modules/instagram-private-api/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/ig-upload/node_modules/instagram-private-api/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/usr/local/lib/node_modules/ig-upload/node_modules/instagram-private-api/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/usr/local/lib/node_modules/ig-upload/node_modules/instagram-private-api/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/ig-upload/node_modules/instagram-private-api/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/usr/local/lib/node_modules/ig-upload/node_modules/instagram-private-api/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/ig-upload/node_modules/instagram-private-api/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/ig-upload/node_modules/instagram-private-api/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/usr/local/lib/node_modules/ig-upload/node_modules/instagram-private-api/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._settlePromise (/usr/local/lib/node_modules/ig-upload/node_modules/instagram-private-api/node_modules/bluebird/js/release/promise.js:582:21)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/ig-upload/node_modules/instagram-private-api/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/ig-upload/node_modules/instagram-private-api/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/usr/local/lib/node_modules/ig-upload/node_modules/instagram-private-api/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._settlePromise (/usr/local/lib/node_modules/ig-upload/node_modules/instagram-private-api/node_modules/bluebird/js/release/promise.js:582:21)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/ig-upload/node_modules/instagram-private-api/node_modules/bluebird/js/release/promise.js:614:10)

⠙
```

im using node version 6.11.2

**Comment by cagrio** [comment]
same here. have you managed the solve the issue?

**Comment by manuhank** [comment]
nope. but i have not tried very much.

**Comment by aranajhonny** [comment]
sorry I have not had time to fix it, if you want you can collaborate to use https://github.com/jlobos/instagram-web-api/
